[build]
  functions = "functions"
  publish = "."
  
[dev]
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"
